### ISSUE TITLE
--generate-interpolation broken in v1.0.2

### ISSUE THREAD

**Issue by zax9** [lucidrains/stylegan2-pytorch#138]
Tried running a --generate-interpolation in the latest version, got the below error. Generating a single image with --generate works fine.

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/bin/stylegan2_pytorch", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 152, in main
    fire.Fire(train_from_folder)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 136, in train_from_folder
    model.generate_interpolation(samples_name, num_image_tiles, save_frames = save_frames)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 992, in generate_interpolation
    latents_low = noise(num_rows ** 2, latent_dim)
TypeError: noise() missing 1 required positional argument: 'device'

```

**Comment by lucidrains** [comment]
@zax9 ah sorry, turns out I patched that bug from 1.0.2 -> 1.0.3

if you are daring, you can open up the text editor on the file you have above locally (/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py) and change two lines like so

https://github.com/lucidrains/stylegan2-pytorch/commit/62a83e16188ed570e6c16ea6270667f9b44297d6#diff-f349fc90fef54f7670abfd666216fdfaR1012

**Comment by lucidrains** [comment]
@zax9 ohh nvm, actually I think it should work on 1.0.2! Are you sure you are not on that version?

**Comment by zax9** [comment]
I ran a "pip install stylegan2_pytorch" just before opening the issue, but unfortunately I have terminated the EC2 instance I was using. I'll spin up another one and try again and see if the issue repros.

**Comment by lucidrains** [comment]
@zax9 ok, try `pip install syylegan2_pytorch==1.0.2`, I think it should work

**Comment by zax9** [comment]
Well, on a new ec2 instance I wasn't able to repro my original issue, and --generate-interpolation seems to work correctly on 1.0.2. However, on 1.0.3 I get an entirely new error. I just installed 1.0.2, ran --generate-interpolation successfully, installed 1.0.3 and ran again and it failed, then downgraded to 1.0.2 and ran again and it succeeded. I don't know if you want a separate issue opened for this or not, but here's the error I got with 1.0.3:

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/bin/stylegan2_pytorch", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 157, in main
    fire.Fire(train_from_folder)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/stylegan2_pytorch/cli.py", line 139, in train_from_folder
    model.load(load_from)
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/stylegan2_pytorch/stylegan2_pytorch.py", line 1104, in load
    self.GAN.load_state_dict(load_data['GAN'])
  File "/home/ubuntu/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for StyleGAN2:
        Missing key(s) in state_dict: "G.blocks.0.to_rgb.upsample.1.f", "G.blocks.1.to_rgb.upsample.1.f", "G.blocks.2.to_rgb.upsample.1.f", "G.blocks.3.to_rgb.upsample.1.f", "G.blocks.4.to_rgb.upsample.1.f", "G.blocks.5.to_rgb.upsample.1.f", "D.blocks.0.downsample.0.f", "D.blocks.0.downsample.1.weight", "D.blocks.0.downsample.1.bias", "D.blocks.1.downsample.0.f", "D.blocks.1.downsample.1.weight", "D.blocks.1.downsample.1.bias", "D.blocks.2.downsample.0.f", "D.blocks.2.downsample.1.weight", "D.blocks.2.downsample.1.bias", "D.blocks.3.downsample.0.f", "D.blocks.3.downsample.1.weight", "D.blocks.3.downsample.1.bias", "D.blocks.4.downsample.0.f", "D.blocks.4.downsample.1.weight", "D.blocks.4.downsample.1.bias", "D.blocks.5.downsample.0.f", "D.blocks.5.downsample.1.weight", "D.blocks.5.downsample.1.bias", "D.blocks.6.downsample.0.f", "D.blocks.6.downsample.1.weight", "D.blocks.6.downsample.1.bias", "GE.blocks.0.to_rgb.upsample.1.f", "GE.blocks.1.to_rgb.upsample.1.f", "GE.blocks.2.to_rgb.upsample.1.f", "GE.blocks.3.to_rgb.upsample.1.f", "GE.blocks.4.to_rgb.upsample.1.f", "GE.blocks.5.to_rgb.upsample.1.f", "D_aug.D.blocks.0.downsample.0.f", "D_aug.D.blocks.0.downsample.1.weight", "D_aug.D.blocks.0.downsample.1.bias", "D_aug.D.blocks.1.downsample.0.f", "D_aug.D.blocks.1.downsample.1.weight", "D_aug.D.blocks.1.downsample.1.bias", "D_aug.D.blocks.2.downsample.0.f", "D_aug.D.blocks.2.downsample.1.weight", "D_aug.D.blocks.2.downsample.1.bias", "D_aug.D.blocks.3.downsample.0.f", "D_aug.D.blocks.3.downsample.1.weight", "D_aug.D.blocks.3.downsample.1.bias", "D_aug.D.blocks.4.downsample.0.f", "D_aug.D.blocks.4.downsample.1.weight", "D_aug.D.blocks.4.downsample.1.bias", "D_aug.D.blocks.5.downsample.0.f", "D_aug.D.blocks.5.downsample.1.weight", "D_aug.D.blocks.5.downsample.1.bias", "D_aug.D.blocks.6.downsample.0.f", "D_aug.D.blocks.6.downsample.1.weight", "D_aug.D.blocks.6.downsample.1.bias".
        Unexpected key(s) in state_dict: "D.blocks.0.downsample.weight", "D.blocks.0.downsample.bias", "D.blocks.1.downsample.weight", "D.blocks.1.downsample.bias", "D.blocks.2.downsample.weight", "D.blocks.2.downsample.bias", "D.blocks.3.downsample.weight", "D.blocks.3.downsample.bias", "D.blocks.4.downsample.weight", "D.blocks.4.downsample.bias", "D.blocks.5.downsample.weight", "D.blocks.5.downsample.bias", "D.blocks.6.downsample.weight", "D.blocks.6.downsample.bias", "D_aug.D.blocks.0.downsample.weight", "D_aug.D.blocks.0.downsample.bias", "D_aug.D.blocks.1.downsample.weight", "D_aug.D.blocks.1.downsample.bias", "D_aug.D.blocks.2.downsample.weight", "D_aug.D.blocks.2.downsample.bias", "D_aug.D.blocks.3.downsample.weight", "D_aug.D.blocks.3.downsample.bias", "D_aug.D.blocks.4.downsample.weight", "D_aug.D.blocks.4.downsample.bias", "D_aug.D.blocks.5.downsample.weight", "D_aug.D.blocks.5.downsample.bias", "D_aug.D.blocks.6.downsample.weight", "D_aug.D.blocks.6.downsample.bias".

```

I can open a new issue for this if you'd like.

**Comment by lucidrains** [comment]
@zax9 yup, unfortunately I introduced a breaking change by accident :( i'll revert that and move it to v1.1 instead

**Comment by lucidrains** [comment]
@zax9 ok, if you update to 1.0.4, it should be all fine now. 1.1 would require you to retrain though, so keep on the 1.0.x line

**Comment by lucidrains** [comment]
@zax9 what are you training on? :D

**Comment by zax9** [comment]
In terms of dataset or equipment?

**Comment by lucidrains** [comment]
Dataset I mean

**Comment by zax9** [comment]
Approximately 1,000 hand-edited, centered, and scaled 256x256 licensed stock photography images. Trying to replicate the "this ____ does not exist" type of thing.

**Comment by lucidrains** [comment]
maybe with a couple GTX 3090's, you'll be able to :)
